### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by nzsjb** [nohajc/netflix-mitm-proxy#3]
Where does the msl_decrypt.py file have to go?

I'm not familiar with Python so this is in idiot question but I've tried many different locations and just keep getting the following message when I try to run mitmdump

C:\Users\User>mitmdump -s msl_decrypt.py
C:\Users\User\AppData\Local\Programs\Python\Python37-32\Scripts\mitmdump: No such script

I can successfully run mitmdump without the script.

**Comment by nohajc** [comment]
Shouldn't really matter where the script goes. Just make sure the path is correct. If you run mitmdump from the directory where the script is located, it should work. Also, you can try with absolute path instead of relative: e. g. mitmdump -s C:\Users\User\repository\msl_decrypt.py

Also make sure you followed the installation instructions for Windows, i.e. install mitmproxy with pip or inside WSL (in case of WSL, you would use bash shell instead of cmd).

**Comment by nzsjb** [comment]
Thanks for the quick reply.

I used an absolute path and it's worked, just fine. Got a log file and it's proving very useful. Great addition to mitmdump.

**Comment by nohajc** [comment]
Good to hear. Thanks for appreciation!
